### ISSUE TITLE
Emmet

### ISSUE THREAD

**Issue by tenhobi** [surdu/selector-to-tag#10]
Do you know Emmet http://emmet.io/ ?

It does this and much more... You even can write something like `nav>ul>li*7>a[#x$]{link $$}`.

So ... isn't this kind of redundant?

**Comment by dsandstrom** [comment]
For me, Emmet does too much.  I only want the functionality that this package provides, not Emmet's bloat.

**Comment by surdu** [comment]
No, didn't know about Emmet.

I don't see myself using CSS selectors to write that much HTML structure at once. If there are people that like that, then Emmet will clearly be a perfect solution.

I'll give it a try, nevertheless :)

Thanks for sharing.

**Comment by tenhobi** [comment]
:+1:
