### ISSUE TITLE
Allow user-defined file extensions

### ISSUE THREAD

**Issue by itsjustmath** [surdu/selector-to-tag#12]
Love the concept! Small feature request...I work a lot with [handlebars](http://handlebarsjs.com/) templates (which currently aren't supported). It would be awesome if you did something similar to what [emmet does](https://github.com/emmetio/emmet-atom#tab-key):

> 1. Use Open Your Keymap menu item to open your custom keymap.cson file.
> 2. Add the following section into it:
> 
> ``` '
> atom-text-editor[data-grammar="YOUR GRAMMAR HERE"]:not([mini])':
>     'tab': 'emmet:expand-abbreviation-with-tab'
> ```
> 
> Replace YOUR GRAMMAR HERE with actual grammar attribute value. The easiest way to get grammar name of currently opened editor is to open DevTools and find corresponding <atom-text-editor> element: it will contain data-grammar attribute with value you need. For example, for HTML syntax it’s a text html basic.

**Comment by surdu** [comment]
If I'm not wrong about what I think you're saying, selector-to-tag already has this feature. In the settings of the package you can set on what file extensions the package should bind on. 

The setting you are looking for is called `File Extensions`.

You can find a complete list of options and their description here: https://github.com/surdu/selector-to-tag#options

Was this what you where looking for ?

**Comment by itsjustmath** [comment]
I think so. Where would I find this setting, `config.cson`? Can you provide an example for how to set these file extensions?

**Comment by surdu** [comment]
`Atom > Preferences > Packages`, in the list search for `selector-to-tag` and press the `Settings` button.

**Comment by itsjustmath** [comment]
Thanks for your help!

**Comment by surdu** [comment]
My pleasure :wink:
