### ISSUE TITLE
Multiple tags at once

### ISSUE THREAD

**Issue by hackn101** [surdu/selector-to-tag#13]
Hi this is not an issue  but I am new to github so I didn't know where to put this. 

I wanted to suggest the option to make multiple tags at once. For instance  

foo.bar*3

would make (3)  <foo class="bar"></foo> elements. 

Is this something that is being worked on or thought of? I just think that would be awesome. especially for things like the <li> tags. <img> tags and so forth

I would have contributed myself but I don't know much about json

Thanks for listening,

**Comment by surdu** [comment]
I'll consider it for the next version :wink:

**Comment by hackn101** [comment]
Sweet man. I love this this package. Looking forward to the next version.

**Comment by surdu** [comment]
After some deliberation I decided to not implement this, but rather keep it as simple as possible. The  package should give you the building blocks for creating any structure you like, and usually this is the workflow I believe most developer take: designing one element at a time.

If in the future, if I come to the conclusion that this might not be the case, this and other similar tickets will join the pool of mass-production features.
