### ISSUE TITLE
Property solver

### ISSUE THREAD

**Issue by jesseflorig** [surdu/selector-to-tag#15]
`foo[name=bar]` solves to `<foo name="bar"></foo>`

**Comment by surdu** [comment]
You've mentioned there the perfect scenario. What about a less perfect scenario: `input[name=bar]`. This will solve to `<input name="bar" />` which is exactly the same output as if you typed `input`, solved this into a tag and then typed the attribute (you only maybe save one key stroke, the one time you have to press the double quotes to print out the pair of double quotes of the value of the attribute).

What will help in your case is what I've described in #16 : after you solve a block tag, first put the cursor just in place to enter attributes (properties) for the solved tag and then pressing tab again to jump you in place to type the tag content.

If you feel necessary, please reopen the issue.

**Comment by surdu** [comment]
PS: #16 will help achieve what you needed here. Coming soon :)
