### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by shippin** [surdu/selector-to-tag#19]
Is there anything I need to do for this to work?

Do I need to create the TAB shortcut myself?

Thanks!
Yonatan

**Comment by surdu** [comment]
No, this should work "out of the box". 

Be aware of the files that this extension operates in. These are the default file extensions the selector-to-tag will operate in: htm, html, kit, shtml, tmpl, tpl, xhtml.

If you want, you can set your own extensions in the settings of the selector-to-tag package.

**Comment by surdu** [comment]
If you still have problems, please feel free to reopen this.
