### ISSUE TITLE
Attribute selector completion

### ISSUE THREAD

**Issue by chenasraf** [surdu/selector-to-tag#20]
I remember using JetBrains products, and there you could do something like this:

`input[type=checkbox][placeholder=test]`<kbd>TAB</kbd>

Which would complete to:

`<input type="checkbox" placeholder="test" />`

I think it could be really useful here.

**Comment by surdu** [comment]
Hello,

Thank you for your suggestion, but it was previously addressed here: https://github.com/surdu/selector-to-tag/issues/5#issuecomment-97077846

**Comment by chenasraf** [comment]
If I developed this would you be reluctant to merge? Because I think it's particularly useful since:
- We place the cursor inside the tag and not in the attributes so this causes you to do extra moving around
- It shouldn't degrade the regular experience only add to it if one wants
- It would make it easier to copy/paste CSS and use it directly

**Comment by surdu** [comment]
Moving the cursor in the attribute region for block elements is already planned (#16).

It does not degrade the regular experience of users, but comparing the fact that the code has to be maintained and future-supported with the fact that it doesn't add much value it makes me reluctant to add it to the extension, sorry :( .
