### ISSUE TITLE
Nested elements

### ISSUE THREAD

**Issue by dcporter44** [surdu/selector-to-tag#22]
It would be great to be able to use the > CSS selector to create nested elements. For example div>div would result in one div nested in another. And the + selector can create siblings.

Also,
I saw a previous issue where you thought saying div[template=test] wouldn't be helpful, but why? Its quicker than writing <div template="test"></div>

Anyway, big fan of this package, so thanks!

**Comment by surdu** [comment]
Hello and sorry for the late response, somehow I missed the notification for this issue 😞 .

The goal of this plugin is to provide basic building blocks that will allow you to achieve any other structure. In your example, usually you take care of one div at a time, like adding the appropriate class and id for each.

As for your second point, I agree, but I found a more elegant solution for this described in #16 😄  

Thank you very much for your feedback, much appreciated, and sorry again for being so very late with the answer.
