### ISSUE TITLE
Can't use snippet in html tags anymore

### ISSUE THREAD

**Issue by dsandstrom** [surdu/selector-to-tag#28]
I used to be able to use tab completion for snippets inside of html tags, however a recent change has impacted that ability.  When you have your cursor inside of a tag (<div |>`) and hit tab, nothing happens.  Your package is trying to solve a tag when instead it should be passing the keystroke to snippets.

**Comment by surdu** [comment]
After a recent fix (for #14) I was expecting quite the opposite: to fallback to snippets more often.

That fix is causing some other problem as well, so I'll have to find another fix for it.

Thank you for the heads up! I don't use snippets in HTML so this would have gone unnoticed 😉

**Comment by dsandstrom** [comment]
Thank you for looking into it.  I mostly use snippets to add erb/php tags inside of html.
