### ISSUE TITLE
Expand a dot to a div

### ISSUE THREAD

**Issue by dsandstrom** [surdu/selector-to-tag#4]
Is it possible to expand a period to a div tag?  So: `.my-class` -> `<div class="my-class">...`

**Comment by surdu** [comment]
For now no, but sounds like a good idea. I'll give it a try and see how it feels. I'll update this issue to keep you posted. Thanks for the feedback !

**Comment by dsandstrom** [comment]
Just to be clear, # should expand to an id.

**Comment by surdu** [comment]
@dsandstrom I'm afraid I don't understand what you mean ...

**Comment by dsandstrom** [comment]
I'm adding to my request. 
`#test` -> `<div id="test">`
`#test.class` -> `<div id="test" class="class">`

**Comment by surdu** [comment]
That should already work like this.

**Comment by dsandstrom** [comment]
`div#test` works.  But I would like `#test` to expand to a div tag with the id of "test".  I will take a shot at this this weekend.

**Comment by surdu** [comment]
My bad,  I missed that detail :)
