### ISSUE TITLE
Expand block tags to multiple lines

### ISSUE THREAD

**Issue by dsandstrom** [surdu/selector-to-tag#6]
div.test expands to
`<div class="test"></div>`
I'd prefer

```
<div class="test">
  |
</div>
```

It'll save me time by removing extra key presses (enter, shift-enter).

**Comment by surdu** [comment]
Makes sense. I'll add an option for whoever wants to keep the current behavior (like myself :smile: )

**Comment by dsandstrom** [comment]
After using this, I don't like having h1-h6 expand to multiple lines.  My headings are usually only one line long and probably the same for most people.  I'll send you a PR to remove them from the default.

**Comment by surdu** [comment]
I removed them myself as I was fixing the other bug you've filled. Hope it's the same to you.
